FROM python:3.8
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./lib_catalog .
RUN pip3 install django && \
    pip3 install -r requirements.txt
CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000